name:                how-these-things-work
version:             0.1.0.0
github:              "vrnvu/how-these-things-work"
license:             BSD3
author:              "Arnau Diaz"

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5

library:
  exposed-modules: UniversalMachine
  source-dirs: src
  ghc-options: -Wall

tests:
  how-these-things-work-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - how-these-things-work
    - hspec
